### PR TITLE
Test with Gemoji 4.0.x as well

### PR DESCRIPTION
**Pull request by ashmaroli**
https://github.com/github/gemoji/releases/tag/v4.0.0.pre0

### CODE REVIEW

**Comment by ashmaroli** [comment]
IMO, this **shouldn't be merged** until `gemoji-4.0.0` has been released..

**Review by maxim85200 — APPROVED** [review]

**Comment by bewuethr** [comment]
[gemoji 4.0.0](https://github.com/github/gemoji/releases/tag/v4.0.0) has been released today 😃

**Comment by ashmaroli** [comment]
@bewuethr Thanks for letting us know.
Before proceeding, this repository needs to set up CI via GitHub Actions first.

**Comment by parkr** [comment]
Adding Actions CI workflow in #127

**Comment by parkr** [comment]
This is taken care of in #131. There's some optimization for our CI now (there are 8 actions since the matrix is 2x2x2) but otherwise we're ready to go! We can release a v0.13.0 or a v1.0.0 which allow gemoji v3 and v4.

**Pull request closed without merging**
