### PR TITLE
Drop dependency on ActiveSupport

### PR DESCRIPTION
**Pull request by ashmaroli**
..as it will be handled by `html-pipeline`..

### CODE REVIEW

**Comment by DirtyF** [comment]
... https://github.com/jch/html-pipeline/blob/master/html-pipeline.gemspec#L17

**Comment by ashmaroli** [comment]
We require at least `Ruby 2.3.0`.. so older versions of `activesupport` will be filtered out automatically..

**Comment by pathawks** [comment]
We only started explicitly requiring `activesupport` in https://github.com/jekyll/jemoji/pull/47 because they dropped support for Ruby 2.2 but we still wanted to support it. I don't think we need to lock down the version of `activesupport` anymore.

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
