### PR TITLE
Update Gemoji Version

### PR DESCRIPTION
**Pull request by mmartinson**
This should solve #53.

I can coordinate with @misha-abasov to QA with his site on a fork of Jekyll and I'll post an update here.

### CODE REVIEW

**Comment by naftulikay** [comment]
I am affected by this. Can we merge this now that Gemoji is 3.0.0?

**Comment by benbalter** [comment]
I'd prefer not to add a rc to the gemspec, but if 3.0.0 stable is out, and tests pass, glad to merge here or in a new PR.

**Comment by naftulikay** [comment]
@benbalter thank you for your speedy reply, I will probably supply a pull request from my fork.

**Comment by naftulikay** [comment]
@benbalter I have created #55 to update to stable Gemoji 3.0.

**Comment by benbalter** [comment]
Closing in favor of #55.

**Pull request closed without merging**
